nels-dev/csis3275-proj

src/main/java/csis3275/project/HelloController.java, src/test/java/csis3275/project/HelloControllerTest.java
=> [Pj-003] add feature

.circleci/config.yml, pom.xml, src/main/java/csis3275/project/seasell/HelloController.java, src/main/java/csis3275/project/seasell/WebApplication.java, src/test/java/csis3275/project/seasell/HelloControllerTest.java
+ update CI config to filter only main branch for deployment tasks
+ add project name "SeaSell" to packages and pom.xml
=> Add project name and CI config change

README.md, pom.xml, src/main/java/csis3275/project/seasell/HelloController.java, src/main/java/csis3275/project/seasell/WebApplication.java, src/main/java/csis3275/project/seasell/sample/SampleController.java, src/main/java/csis3275/project/seasell/sample/model/Sample.java, src/main/java/csis3275/project/seasell/sample/repository/SampleRepository.java, src/main/java/csis3275/project/seasell/sample/service/SampleService.java, src/main/resources/application-sit.yml, src/main/resources/application.yml, src/test/java/csis3275/project/seasell/HelloControllerTest.java
+ DB setup for local and cloud
+ added Sample module
+ added Readme content
=> Project setup: DB and Readme content

frontend/package-lock.json, frontend/src/components/RegistrationForm.vue, frontend/src/components/SigninForm.vue, frontend/src/router/index.js, frontend/src/services/user.service.js, frontend/src/views/RegistrationPage.vue, frontend/src/views/SignIn.vue, src/main/java/csis3275/project/seasell/configuration/JWTAuthenticationFilter.java, src/main/java/csis3275/project/seasell/user/RegistrationController.java, src/main/java/csis3275/project/seasell/user/dto/LoginRequest.java, src/main/java/csis3275/project/seasell/user/dto/LoginResponse.java, src/main/java/csis3275/project/seasell/user/dto/UserDto.java, src/main/java/csis3275/project/seasell/user/model/AppUser.java, src/main/java/csis3275/project/seasell/user/repository/UserRepository.java, src/main/java/csis3275/project/seasell/user/service/UserService.java
**Create:** 
1. Registration Controller 
2. User DTO
**Edit:**
1. UserService (With duplicate email validation)
**Create:** 
1. Registration Form component (With email and password validation)
2. Registration Page view
**Edit**
1. router - index.js
2. services - user.service.js
=> Registration Frontend and Backend Update

frontend/src/views/ClientMarketplace.vue, frontend/src/views/MainPage.vue
changed the avatar to see my store
=> changed the avatar

frontend/package-lock.json, frontend/src/components/HeaderPage.vue, frontend/src/components/RegistrationForm.vue, frontend/src/views/RegistrationPage.vue, src/main/java/csis3275/project/seasell/user/repository/UserRepository.java, src/main/java/csis3275/project/seasell/user/service/UserService.java
1. Add validation
2. FormAlert adjustment
=> [SS-9]Registration Frontend Update:

frontend/src/App.vue, frontend/src/components/HeaderPage.vue, frontend/src/components/RegistrationForm.vue, frontend/src/components/ToastAlert.vue, frontend/src/store/alert.module.js, src/main/java/csis3275/project/seasell/user/service/UserService.java
1. Logout method from logout button
2. ToastAlert color (green and red)
=> [SS-83] Logout Frontend Update:

frontend/src/services/store.service.js, src/main/java/csis3275/project/seasell/product/StoreController.java, src/main/java/csis3275/project/seasell/product/dto/ProductDto.java, src/main/java/csis3275/project/seasell/product/model/Product.java, src/main/java/csis3275/project/seasell/product/repository/ProductRepository.java, src/main/java/csis3275/project/seasell/product/service/ProductService.java, src/main/java/csis3275/project/seasell/user/UserController.java, src/main/java/csis3275/project/seasell/user/dto/UserDto.java, src/main/java/csis3275/project/seasell/user/model/AppUser.java, src/main/resources/data.sql
=> added get products by current user

frontend/README.md, frontend/src/App.vue, frontend/src/components/FooterPage.vue, frontend/src/components/HeaderPage.vue, frontend/src/components/ProductForm.vue, frontend/src/components/SigninForm.vue, frontend/src/components/ToastAlert.vue, frontend/src/plugins/vuetify.js, frontend/src/services/axios.js, frontend/src/views/MainPage.vue
Added a theme into Vuetify. 
All other component configurations should rely on theme color tokens eg. `primary`, `secondary`, etc.
=> Configure theme for Vuetify

frontend/package-lock.json, frontend/src/components/CheckoutModal.vue, frontend/src/components/ProductForm.vue
=> SS-58 Checkout

frontend/package-lock.json, frontend/package.json, frontend/src/components/EditProductForm, frontend/src/components/SellerProductCard.vue, frontend/src/components/SellerProductCardForm.vue, frontend/src/router/index.js, frontend/src/services/product.service.js, frontend/src/store/index.js, frontend/src/store/mystore.module.js, frontend/src/views/EditProductPage.vue, src/main/java/csis3275/project/seasell/product/ProductController.java, src/main/java/csis3275/project/seasell/product/StoreController.java, src/main/java/csis3275/project/seasell/product/model/Product.java
SS-88 productListedUnlisted
- Update Product Card UI
- Toggle product status listed to unlisted, and vice versa
- Update product list after status changes
=> Ss 88 product listed unlisted

frontend/src/components/AdminDeposits.vue, frontend/src/components/AdminWithdrawals.vue, frontend/src/components/CheckoutModal.vue, frontend/src/components/DepositRequests.vue, frontend/src/components/WithdrawalRequests.vue, frontend/src/services/account.service.js, frontend/src/services/axios.js, frontend/src/views/AdminDashboard.vue, src/main/java/csis3275/project/seasell/account/AdminDepositRequestController.java, src/main/java/csis3275/project/seasell/account/AdminWithdrawalRequestController.java, src/main/java/csis3275/project/seasell/account/dto/RequestStatusChangeDto.java, src/main/java/csis3275/project/seasell/account/service/DepositRequestService.java, src/main/java/csis3275/project/seasell/account/service/WithdrawRequestService.java, src/main/java/csis3275/project/seasell/common/exception/InvalidStateException.java, src/main/resources/data.sql
[Kapture 2023-03-06 at 09.52.40.webm](https://user-images.githubusercontent.com/101234025/223191784-ab4c773a-24b7-4d32-8d10-8af5ec97097c.webm)
=> [SS-74] to [SS-81] Admin user to fulfill or reject financial requests

frontend/src/components/SigninForm.vue, frontend/src/components/WithdrawalRequestForm.vue, src/main/java/csis3275/project/seasell/account/service/JournalEntryService.java
- fix login with Firefox
- Withdrawal details should only accept digits in the account number
- fixed typo
=> [SS-86][SS-93] UI fixes

frontend/src/components/EditProductForm.vue, frontend/src/components/SellerProductCard.vue, frontend/src/views/CreateProductPage.vue
- Align create product page and edit product page wording
- Align both pages format
- Show edit button only when product status is LISTED and UNLISTED
- Status change button update, from LISTED -> UNLISTED (and vice versa), Ordered -> Shipped, Shipped -> Delivered
=> SS-91 Edit Product Page Format Alignment

frontend/src/components/EditProductForm.vue, frontend/src/components/SellerProductCard.vue, frontend/src/services/account.service.js, frontend/src/services/product.service.js, frontend/src/services/store.service.js, frontend/src/views/CreateProductPage.vue, src/main/java/csis3275/project/seasell/account/AdminDepositRequestController.java, src/main/java/csis3275/project/seasell/account/AdminWithdrawalRequestController.java, src/main/java/csis3275/project/seasell/product/ProductController.java, src/main/java/csis3275/project/seasell/product/StoreController.java, src/main/java/csis3275/project/seasell/product/service/ProductService.java, src/test/java/csis3275/project/seasell/product/ProductControllerTest.java
Adjust endpoint path for consistency
=> Endpoint path adjustment

frontend/src/components/HeaderPage.vue, frontend/src/components/OrderTable.vue, frontend/src/router/index.js, frontend/src/services/order.service.js, frontend/src/views/EditProductPage.vue, frontend/src/views/MyOrderPage.vue, src/main/java/csis3275/project/seasell/order/OrderController.java, src/main/java/csis3275/project/seasell/order/dto/OrderDto.java, src/main/java/csis3275/project/seasell/order/model/Order.java, src/main/java/csis3275/project/seasell/order/repository/OrderRepository.java, src/main/java/csis3275/project/seasell/order/service/OrderService.java
- Create order page
- Display all ordered orders summary
- Update backend and frontend
=> SS-64 My Order Page

frontend/src/components/EditProductForm.vue, frontend/src/services/order.service.js
=> SS-90 Edit Product Page

frontend/src/components/OrderTable.vue, frontend/src/services/order.service.js, src/main/java/csis3275/project/seasell/common/ImagesController.java, src/main/java/csis3275/project/seasell/common/dto/FileWrapper.java, src/main/java/csis3275/project/seasell/common/service/CloudStorageFileService.java, src/main/java/csis3275/project/seasell/common/service/FileService.java, src/main/java/csis3275/project/seasell/common/service/LocalStorageFileService.java, src/main/java/csis3275/project/seasell/order/OrderController.java, src/main/java/csis3275/project/seasell/order/dto/OrderDto.java, src/main/java/csis3275/project/seasell/order/dto/OrderStatusUpdateDto.java, src/main/java/csis3275/project/seasell/order/model/Order.java, src/main/java/csis3275/project/seasell/order/model/OrderStatus.java, src/main/java/csis3275/project/seasell/order/repository/OrderRepository.java, src/main/java/csis3275/project/seasell/order/service/OrderService.java, src/test/java/csis3275/project/seasell/common/ImagesControllerTest.java, src/test/java/csis3275/project/seasell/common/service/LocalStorageFileServiceTest.java
- When client confirm order, update order status, product status, buyer's on-hold balance and seller's credit balance
- Optimize image fetching by introducing cache
=> [SS-96] update product status to completed and release credit

src/main/java/csis3275/project/seasell/order/OrderController.java, src/main/java/csis3275/project/seasell/order/dto/OrderDto.java, src/main/java/csis3275/project/seasell/order/repository/OrderRepository.java, src/main/java/csis3275/project/seasell/order/service/OrderService.java, src/main/java/csis3275/project/seasell/product/StoreController.java, src/main/java/csis3275/project/seasell/product/dto/ProductDto.java, src/main/java/csis3275/project/seasell/product/service/ProductService.java
API for getting buyer info (name, address, email) by productId. OrderDto adjustments
=> add endpoint for getBuyerInfoByProductId and some adjustments

frontend/src/components/CurrentOrderBox.vue, frontend/src/components/DeliveredModal.vue, frontend/src/components/OrderTable.vue, frontend/src/components/ProductForm.vue, frontend/src/components/ShipModal.vue, frontend/src/services/order.service.js, frontend/src/services/store.service.js, frontend/src/views/ProductDetailsPage.vue, src/main/java/csis3275/project/seasell/order/OrderController.java, src/main/java/csis3275/project/seasell/order/dto/OrderDto.java, src/main/java/csis3275/project/seasell/order/dto/OrderStatusUpdateDto.java, src/main/java/csis3275/project/seasell/order/model/Order.java, src/main/java/csis3275/project/seasell/order/repository/OrderRepository.java, src/main/java/csis3275/project/seasell/order/service/OrderService.java, src/main/java/csis3275/project/seasell/product/StoreController.java, src/main/java/csis3275/project/seasell/product/dto/ProductDto.java, src/main/java/csis3275/project/seasell/product/model/Product.java, src/main/java/csis3275/project/seasell/product/service/ProductService.java, src/main/java/csis3275/project/seasell/user/model/AppUser.java
- UI of ProductForm adjusted, added `CurrentOrderBox` component
- Some endpoint movement to put all seller centric endpoints in `StoreController`
=> [ss-94] Buyer to see shipment reference in product details page

frontend/src/components/BuyerInfoModal.vue, frontend/src/components/ProductForm.vue
=> buyer info ui

.circleci/config.yml, .github/workflows/build-test.yml, .github/workflows/node.js.yml, src/main/java/csis3275/project/seasell/account/ClientDepositRequestController.java, src/main/java/csis3275/project/seasell/account/dto/WithdrawalRequestDto.java, src/main/java/csis3275/project/seasell/account/service/BalanceAccountService.java, src/main/java/csis3275/project/seasell/common/ImagesController.java, src/main/java/csis3275/project/seasell/common/service/CloudStorageFileService.java, src/main/java/csis3275/project/seasell/common/service/FileService.java, src/main/java/csis3275/project/seasell/common/service/LocalStorageFileService.java, src/main/java/csis3275/project/seasell/order/service/OrderService.java, src/test/java/csis3275/project/seasell/account/service/BalanceAccountServiceTest.java, src/test/java/csis3275/project/seasell/account/service/DepositRequestServiceTest.java, src/test/java/csis3275/project/seasell/account/service/WithdrawRequestServiceTest.java
- Added unit tests to the Account module 
- Added GitHub workflow for testing and reporting coverage
=> [ss-104] add tests to account module components

frontend/src/views/CreateProductPage.vue
should not allow nagative values, and redirect back to mystore
=> validation added

frontend/src/components/ProfileForm.vue
- mobile validation with numeric and maxLength
=> [SS-110] ProfilePageValidation
